title:            YoungInnovations
description:      Company website
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://younginnovations.com.np
encoding:         UTF-8
disqus_shortname:

# Owner/author information
owner:
  name:           YoungInnovations
  avatar:         bio-photo.jpg
  bio:            "Describe your self."
  email:          info@yipl.com.np
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        yipl
  facebook:       younginnovations
  github:         younginnovations
  stackoverflow:
  linkedin:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: <span>O1</span> our story
    url: /ourstory/
  - title: <span>02</span> work
    url: /work/
  - title: <span>03</span> careers
    url: /careers/
  - title: <span>04</span> contact
    url: /contact/
  - title: <span>05</span> what we're up to
    url: /what-we-upto/
  - title: <span>06</span> our blog
    url: http://blog.yipl.com.np
    external: true

staffs:
  - image: /images/staffs/Aayush.png
    name: Aayush Rijal
    designation: Jr. Software Engineer
  - image: /images/staffs/Alina.png
    name: Alina Acharya
    designation: Jr. Data Analyst
  - image: /images/staffs/Anjan.png
    name: Anjan Shrestha
    designation: VP, Product Innovations
  - image: /images/staffs/Anjesh.png
    name: Anjesh Tuladhar
    designation: Chief Innovations Officer
  - image: /images/staffs/Ashish.png
    name: Ashish Ghimire
    designation: Jr. Software Engineer
  - image: /images/staffs/Ashok.png
    name: Ashok Adhikari
    designation: Software Engineer
  - image: /images/staffs/Bibek.png
    name: Bibek Shrestha
    designation: Senior Developer
  - image: /images/staffs/Bibhusan.png
    name: Bibhusan Bista
    designation: CEO
  - image: /images/staffs/Bigyan.png
    name: Bigyan Adhikary
    designation: Jr. Software Engineer
  - image: /images/staffs/Biju.png
    name: Biju Nakarmi
    designation: Sr. Software Engineer
  - image: /images/staffs/Ravi.png
    name: Ravi Putuwal
    designation: Office Aid
  - image: /images/staffs/Deepak.png
    name: Deepak Kumar Shah
    designation: Software Engineer
  - image: /images/staffs/Diken.png
    name: Diken Ulak
    designation: Jr. Software Engineer
  - image: /images/staffs/Geshan.png
    name: Geshan Manandhar
    designation: Co-Founder
  - image: /images/staffs/Julian.png
    name: Julian Raj Manandhar
    designation: Software Engineer
  - image: /images/staffs/Kiran.png
    name: Kiran Shrestha
    designation: Trainee
  - image: /images/staffs/Kopila.png
    name: Kopila Putuwal
    designation: Office Aid
  - image: /images/staffs/Kristina.png
    name: Kristina Shikhrakar
    designation: Intern
  - image: /images/staffs/Kushal.png
    name: Kushal Raj Shrestha
    designation: Software Engineer
  - image: /images/staffs/Lunek.png
    name: Lunek Suwal
    designation: Software Engineer
  - image: /images/staffs/Manish.png
    name: Manish Gopal Singh
    designation: Sr. Software Engineer
  - image: /images/staffs/Manjil.png
    name: Manjil Shrestha
    designation: Trainee
  - image: /images/staffs/Manoj.png
    name: Manoj Byanjankar
    designation: Sr. Software Engineer
  - image: /images/staffs/Nirajan.png
    name: Nirajan Basnet
    designation: Frontend Engineer
  - image: /images/staffs/Prashant.png
    name: Prashant Shrestha
    designation: VP, Business and Technology Innovations
  - image: /images/staffs/Prashanta.png
    name: Prashanta Rimal
    designation: Administration and Finance Officer
  - image: /images/staffs/Pratikshya.png
    name: Pratikshya Rayamajhi
    designation: Operations Innovation Manager
  - image: /images/staffs/Prawesh.png
    name: Prawesh Shrestha
    designation: Manager, Community Innovations
  - image: /images/staffs/Punya.png
    name: Punya Ruchal
    designation: Sr. Web Developer
  - image: /images/staffs/Radhika.png
    name: Radhika Prajapati
    designation: Frontend Engineer
  - image: /images/staffs/Rakeeb.png
    name: Rakeeb Rajbhandari
    designation: Software Engineer
  - image: /images/staffs/Rakesh.png
    name: Rakesh Pradhan
    designation: Sr. Web Developer
  - image: /images/staffs/Rishav.png
    name: Rishav Malla
    designation: Jr. Graphics Designer
  - image: /images/staffs/Rohit.png
    name: Rohit Shrestha
    designation: Designer
  - image: /images/staffs/Sachit.png
    name: Sachit Bir Singh Dangol
    designation: Software Engineer
  - image: /images/staffs/Samita.png
    name: Samita Lalchan
    designation: Community Officer
  - image: /images/staffs/Santosh.png
    name: Santosh Neupane
    designation: System Administrator
  - image: /images/staffs/Saroj.png
    name: Saroj Bista
    designation: Open Data Coordinator
  - image: /images/staffs/Siddharta.png
    name: Siddharta Pachhai
    designation: Intern
  - image: /images/staffs/Sumit.png
    name: Sumit Chhetri
    designation: Sr. Software Engineer
  - image: /images/staffs/Sweta.png
    name: Sweta Shrestha
    designation: Sr. Frontend Engineer
  - image: /images/staffs/Umesh.png
    name: Umesh Basnet
    designation: Jr. Android Developer

collections:
  what-we-upto:
    output: true
    permalink: /:collection/:title/

  blog:
    output: true
    permalink: /:collection/:title/

#  page_collections:
#    output: true
#- projects:
#    permalink: pretty
#- team
#- miscellaneous:
#    source: _upto

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kathmandu
future:      true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/
#paginate_path: 'posts/page:num'
#paginate: 1

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
#  enable_coderay: false
#
#  coderay:
#    coderay_line_numbers:
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
